### ISSUE TITLE
Absurd Koi Fish Spawns

### ISSUE THREAD

**Issue by MusicalRaven** [Ve6om/Caldera#1]
Playing in single player on normal. As of the second night of living by the water, the entire ocean is filled with only koi fish. See attached image. Sheer amount is lagging my game
![Screenshot 2024-09-03 111616](https://github.com/user-attachments/assets/0541a069-d3b6-43fd-a611-3dbf6d77a78b)

**Comment by kiwiphoenix364** [comment]
I have noticed that, I'll look into it

**Comment by kiwiphoenix364** [comment]
hydra's mobs, is made in mcreator and doesn't seem to be supported much anymore (and doesn't add much to the pack) so I believe I'll get rid of it next update
Thanks for the feedback!
